version: '2'
services:
  service-node-express:
    build: ./
    image: server-node-express
    container_name: server-node-express
    environment:
      - PORT=3000
    ports:
      - "3000:3000"